import { Dimensions } from "react-native";
var fullWidth = Dimensions.get("window").width; //full width
var fullHeight = Dimensions.get("window").height; //full height
export var themes = {
    colorApp: "#41855E",
    colorBG: "#FFFF",
    colorGray: "#696A69",
    colorGrayLight: "#A5A7A5",
    colorGrayLight2: "#DBDCDD",
    colorGrayLighter: "#ECEBEA",
    colorGrayLighter2: "#F5F5F5",
    colorYellow: "#FDE202",
    colorOrange: "#E8CC15",
    colorOrange2: "#EEA405",
    colorBlueLight: "#03A3B6",
    colorBlue: "#0D5BA5",
    heightBtn: 35,
    heightBtnSmall: 30,
    sizeText: 16,   
    headerHeight: 54,
    fullWidth: fullWidth,
    fullHeight: fullHeight,
    fontLight: "Exo-Light",
    fontLightItalic: "Exo-LightItalic",
    fontRegular: "Exo-Regular",
    fontItalic: "Exo-Italic",
    fontBold: "Exo-Bold",
    fontBoldItalic: "Exo-BoldItalic",
    font: "Exo",
}